package com.kainos.ea.Models;

import java.util.Objects;

public class Employee {
    private int DeliveryEmpId; // employee number
    protected int salary; // employee salary in pence
    private String name; // employee name
    private String bankNo;
    private String NIN;

    public static final int MIN_SALARY = 7_000_00;

//    public String message1 = String.format("Salary £%,.2f is below the minimum salary £%,.2f.",
//            salary/100.0, MIN_SALARY/100.0);


    public Employee() {

    }

    public Employee(int newNumber)
    {
        setDeliveryEmpId(newNumber);
    }


    public Employee(int newNumber, int newSalary) {
        this(newNumber); // good code calling the constructor again instead of saying the same thing twice
        //setNumber(newNumber); //bad code as your saying same thing twice
        setSalary(newSalary);
    }
    public Employee(int newNumber, int newSalary, String Name, String bankNo, String NIN) {
        this(newNumber, newSalary);
        // this references one of the other constructors
        setName(Name);
        setBankNo(bankNo);
        setNIN(NIN);
    }


    //Number
    public int getDeliveryEmpId() {
        return DeliveryEmpId;
    }

    public boolean setDeliveryEmpId(int thisNumber) {
        if (thisNumber > 0) {
            DeliveryEmpId = thisNumber;
            return true;
        }
        else {
            System.out.println("Needs to be more than 1");
            return false;
        }
    }


//    public boolean setNumber(String thisStringNumber) {
//
//        try{
//            short s = Short.parseShort(thisStringNumber);
//            return setNumber(s);
//        } catch(NumberFormatException e){
//            //throw new BadNumber(e.getMessage());
//        }
//
//        return false;
//    }


    //Salary
    public int getSalary() {
        return salary;
    }



    public void setSalary(int thisSalary) {
//        if (thisSalary > MIN_SALARY) {
//            salary = thisSalary;
//        }
//        else {
//            //throw new SalaryTooLowException(message1);
//
//        }


        salary = thisSalary;
    }

    //Name
    public String getName() {
        return name;
    }

    public boolean setName(String thisName) {
        if (thisName.length() > 2) {
            name = thisName;
            return true;
        }
        else {
            System.out.println("Name must be greater than 2");
        }
        return false;
    }


    public int calcPay()
    {
        return getSalary() /12;
    }

    @Override
    public boolean equals(Object o) {
        Employee employee = (Employee) o;
        return Objects.equals(name, employee.name);
    }

    @Override
    //autogenerated command N
    public String toString() {
        return "Employee{" +
                "number=" + DeliveryEmpId +
                ",salary=" + salary +
                ",name='" + name + '\'' +
                '}';
    }


//    @Override
//    public int compareTo(Employee o) {
//        return Float.compare(this.getSalary(), o.getSalary());
//    }

    public String getBankNo() {
        return bankNo;
    }

    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }

    public String getNIN() {
        return NIN;
    }

    public void setNIN(String NIN) {
        this.NIN = NIN;
    }
}
